import * as maplibregl from './maplibre-gl.js';
const $=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
const fmt=(n,p=1)=>n==null?'Unavailable':Number(n).toFixed(p), signed=n=>n==null?'Unavailable':`${n>0?'+':''}${fmt(n)}`;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const cases={
california:{name:'San Joaquin Valley',region:'UNITED STATES / CALIFORNIA',country:'California, United States',bbox:[-120.99,36.005,-119.7,36.99],orbit:'DESCENDING ORBIT'},
flores:{name:'Flores Island',region:'INDONESIA / EAST NUSA TENGGARA',country:'East Nusa Tenggara, Indonesia',bbox:[121.1,-8.9,121.95,-8.1],orbit:'ASCENDING ORBIT',dates:'12–24 August 2026',track:'168 / 173',strict:0,summary:'No spatially supported pixels survived the strict development quality policy. This audit does not establish earthquake displacement.'},
venezuela:{name:'Coastal Venezuela',region:'VENEZUELA / CARACAS REGION',country:'Northern Venezuela',bbox:[-67.3,10.02,-66.4,10.7],orbit:'ASCENDING ORBIT',dates:'13–25 June 2026',track:'162 / 7',strict:154,summary:'CCS1 has no accepted radar pixels within 500 m. The nearest accepted pixel is about 15.7 km away, so a co-located GNSS validation was not possible.'}};
let research,map,activeCase='california',pairIndex=0,selection=null,markers=[],popup,ready=false,satellite=true;
const pair=()=>research?.pairs[pairIndex];
const details=rows=>`<dl class="details">${rows.map(([k,v,w])=>`<div><dt>${k}</dt><dd${w?' class="warn"':''}>${v}</dd></div>`).join('')}</dl>`;
['#method-nav','#about-link','#limitations-link'].forEach(s=>$(s).onclick=()=>$('#method-dialog').showModal());
$('.dialog-close').onclick=()=>$('#method-dialog').close();
$('#method-dialog').onclick=e=>{if(e.target===$('#method-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
$('#explore-nav').onclick=()=>{selectCase('california');$('#map').scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'});};
function summary(){
selection=null;const c=cases[activeCase],p=pair();if(!p)return;
if(activeCase!=='california'){$('#inspector-content').innerHTML=`<span class="inspector-eyebrow">STUDY AREA / QUALITY AUDIT</span><h2>${c.name}</h2><div class="inspector-location">${c.country}</div><span class="badge">INSUFFICIENT CONFIDENCE</span><div class="metric-main"><label>STRICT QC · SUPPORTED PIXELS</label><div class="metric-number">${c.strict}</div><small>Quality audit only. Not ground motion.</small></div>${details([['Acquisition pair',c.dates],['Track / frame',c.track],['Orbit',c.orbit.split(' ')[0]],['Total uncertainty','Unknown',true]])}<div class="inspector-note">${c.summary}</div><p class="section-label">WHAT YOU’RE SEEING</p><div class="inspector-location">Study-area outline and geographic basemap context. A scientific raster is not published for this case.</div>`;return;}
$('#inspector-content').innerHTML=`<span class="inspector-eyebrow">PAIR ${String(pairIndex+1).padStart(2,'0')} / RESEARCH OVERVIEW</span><h2>Inspect the evidence.</h2><div class="inspector-location">Select a station or click the map<br>to look beneath the surface.</div><span class="badge">VALIDATION NOT PASSED</span><div class="metric-main"><label>GNSS COMPARISON · RMSE</label><div class="metric-number">${fmt(p.rmse)}<span>mm</span></div><small>Radar candidate versus GNSS.<br>This is comparison error, not ground motion.</small></div>${details([['Station comparisons',p.count],['Accepted research pixels',p.accepted.toLocaleString('en-US')],['Reference station','P287'],['Track / frame','042 / 070'],['Total LOS uncertainty','Unknown',true]])}<div class="inspector-note"><strong>Quality is part of the story.</strong><br>Unresolved discrepancies remain. This layer includes interpolated ionosphere for sensitivity research only.</div><p class="section-label">EXPLORE A GNSS STATION</p><div class="station-list">${['P287','P298','P302','CAFR'].map(n=>`<button data-station="${n}">${n} ↗</button>`).join('')}</div>`;
all('[data-station]').forEach(e=>e.onclick=()=>selectStation(e.dataset.station,true));}
function selectStation(name,fly=false){
if(activeCase!=='california')selectCase('california');const s=pair().stations.find(r=>r.station===name);if(!s)return;
selection={type:'station',station:name};const ref=s.role==='reference';
$('#inspector-content').innerHTML=`<button class="return-button" id="back-overview">← Pair overview</button><br><span class="inspector-eyebrow">GNSS STATION / ${ref?'SPATIAL REFERENCE':'INDEPENDENT COMPARISON'}</span><h2>${name}<span class="station-hint">${ref?'REFERENCE':'IGS20'}</span></h2><div class="inspector-location">${s.latitude!=null?`${fmt(s.latitude,4)}° N · ${fmt(Math.abs(s.longitude),4)}° W`:'Location unavailable'}</div><span class="badge">${ref?'REFERENCE · NOT ASSUMED STABLE':'UNVALIDATED LOS CANDIDATE'}</span>${s.unavailable_reason?`<div class="inspector-note">${s.unavailable_reason}</div>`:`<div class="metric-main"><label>${ref?'GNSS LOS CHANGE':'RELATIVE RADAR CANDIDATE'}</label><div class="metric-number">${signed(ref?s.gnss_los_mm:s.relative_nisar_candidate_los_mm)}<span>mm</span></div><small>${ref?'Independent GNSS, projected toward the sensor.':'Toward-positive line-of-sight convention.<br>Not certified ground displacement.'}</small></div>${!ref?`<div class="station-compare"><div><span>GNSS · RELATIVE</span><strong>${signed(s.relative_gnss_los_mm)} <small>mm</small></strong></div><div><span>RESIDUAL</span><strong>${signed(s.residual_mm)} <small>mm</small></strong></div></div>`:''}${details([['Median coherence',fmt(s.median_coherence,3)],['Accepted within 500 m',s.accepted_within_500m],['GNSS formal σ',`${fmt(s.gnss_formal_sigma_mm)} mm`],['Ionospheric component',`${fmt(s.ionospheric_phase_uncertainty_equivalent_mm)} mm`],['Total LOS uncertainty','Unknown',true]])}<div class="inspector-note">${ref?'The measured GNSS reference change is subtracted from each comparison. Local coherence does not prove reference accuracy.':'Radar and GNSS use the same P287 reference. Formal GNSS error and the ionospheric component exclude other systematic errors.'}</div>`}`;
$('#back-overview').onclick=summary;all('.station-marker').forEach(e=>e.classList.toggle('selected',e.dataset.name===name));
if(fly&&s.longitude!=null&&ready)map.flyTo({center:[s.longitude,s.latitude],zoom:10,duration:reduced?0:1000});
if(s.longitude!=null&&ready){popup?.remove();popup=new maplibregl.Popup({offset:14,closeButton:false}).setLngLat([s.longitude,s.latitude]).setText(`${name} · ${ref?'Reference station':'GNSS comparison'}`).addTo(map);}}
function inspectPixel(lng,lat){
if(activeCase!=='california')return;const p=pair(),g=p.grid,b=g.bounds_mercator;
const x=6378137*lng*Math.PI/180,y=6378137*Math.log(Math.tan(Math.PI/4+lat*Math.PI/360));
const col=Math.floor((x-b[0])/(b[2]-b[0])*g.size),row=Math.floor((b[3]-y)/(b[3]-b[1])*g.size);
const value=col>=0&&row>=0&&col<g.size&&row<g.size?g.values[row*g.size+col]:null;
selection={type:'pixel',longitude:lng,latitude:lat,coherence:value};
$('#inspector-content').innerHTML=`<button class="return-button" id="back-overview">← Pair overview</button><br><span class="inspector-eyebrow">MAP INSPECTION / QUALITY LAYER</span><h2>A closer look.</h2><div class="inspector-location">${fmt(lat,5)}° · ${fmt(lng,5)}°</div><span class="badge">RESEARCH COHERENCE ONLY</span><div class="metric-main"><label>AGGREGATED COHERENCE</label><div class="metric-number">${value==null?'—':fmt(value,3)}</div><small>${value==null?'No accepted research data at this location.':'Dimensionless · scale from 0 to 1'}</small></div>${details([['Acquisition pair',`${p.before.slice(5)} → ${p.after.slice(5)}`],['Grid',`${g.size} × ${g.size} visualization`],['Certified displacement','Not available',true],['Total uncertainty','Unknown',true]])}<div class="inspector-note">Spatial averages of accepted NISAR research pixels. High coherence alone does not establish reliable ground displacement. No movement is inferred from this layer.</div>`;
$('#back-overview').onclick=summary;}
function polygon(b){return {type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[b[0],b[1]],[b[2],b[1]],[b[2],b[3]],[b[0],b[3]],[b[0],b[1]]]]}};}
function fit(){if(ready){const b=cases[activeCase].bbox;map.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding:{top:160,bottom:45,left:35,right:40},duration:reduced?0:1200});}}
function updateLayers(){
if(!ready||!research)return;const cal=activeCase==='california',p=pair();
map.getSource('study-area').setData(polygon(cases[activeCase].bbox));map.getSource('coherence').updateImage({url:p.image,coordinates:p.coordinates});
map.setLayoutProperty('coherence-layer','visibility',cal&&$('#coherence-toggle').checked?'visible':'none');map.setPaintProperty('coherence-layer','raster-opacity',Number($('#opacity').value)/100);
markers.forEach(m=>m.remove());markers=[];popup?.remove();
if(cal&&$('#stations-toggle').checked)p.stations.filter(s=>s.longitude!=null).forEach(s=>{const el=document.createElement('button');el.className='station-marker';el.dataset.name=s.station;el.setAttribute('aria-label',`Inspect GNSS station ${s.station}`);el.title=s.station;
if(['P287','P298','P302','CAFR'].includes(s.station))el.classList.add('labeled');if(s.station==='P287')el.classList.add('reference');el.innerHTML=`<i></i><span>${s.station}</span>`;el.onclick=e=>{e.stopPropagation();selectStation(s.station);};markers.push(new maplibregl.Marker({element:el}).setLngLat([s.longitude,s.latitude]).addTo(map));});}
function selectCase(key){
activeCase=key;selection=null;const c=cases[key],cal=key==='california';
all('[data-case]').forEach(e=>{e.classList.toggle('active',e.dataset.case===key);e.setAttribute('aria-pressed',String(e.dataset.case===key));});
$('#map-heading').textContent=c.name;$('#map-breadcrumb').textContent=c.region;$('#map-subtitle').textContent=`${fmt((c.bbox[1]+c.bbox[3])/2,2)}° LAT · ${fmt((c.bbox[0]+c.bbox[2])/2,2)}° LON / ${c.orbit}`;
$('#map-caption').textContent=cal?'COHERENCE / REAL NISAR OBSERVATIONS':'STUDY AREA / GEOGRAPHIC CONTEXT';all('.epoch').forEach(e=>e.disabled=!cal);$('.timeline').classList.toggle('disabled',!cal);['#coherence-toggle','#stations-toggle','#opacity'].forEach(s=>$(s).disabled=!cal);
updateLayers();summary();fit();$('#search-results').hidden=true;$('#search').value='';}
all('[data-case]').forEach(e=>e.onclick=()=>selectCase(e.dataset.case));
all('[data-pair]').forEach(e=>e.onclick=()=>{pairIndex=Number(e.dataset.pair);all('[data-pair]').forEach(b=>{b.classList.toggle('active',b===e);b.setAttribute('aria-pressed',String(b===e));});const old=selection;updateLayers();if(old?.type==='station')selectStation(old.station);else if(old?.type==='pixel')inspectPixel(old.longitude,old.latitude);else summary();});
['#coherence-toggle','#stations-toggle','#opacity'].forEach(s=>$(s).addEventListener('input',updateLayers));$('#reset-view').onclick=fit;
$('#basemap-toggle').onclick=()=>{if(!ready)return;satellite=!satellite;map.setLayoutProperty('satellite','visibility',satellite?'visible':'none');$('#basemap-toggle').setAttribute('aria-label',`Switch to ${satellite?'dark':'satellite'} basemap`);};
$('#layer-collapse').onclick=()=>{const h=!$('#layer-body').hidden;$('#layer-body').hidden=h;$('#layer-collapse').textContent=h?'+':'−';$('#layer-collapse').setAttribute('aria-expanded',String(!h));$('#layer-collapse').setAttribute('aria-label',`${h?'Expand':'Collapse'} map layers`);};
$('#search').addEventListener('input',e=>{const text=e.target.value.trim().toLowerCase(),r=$('#search-results');r.replaceChildren();r.hidden=!text;if(!text)return;
const options=Object.entries(cases).filter(([,c])=>(c.name+' '+c.region+' '+c.country).toLowerCase().includes(text)).map(([key,c])=>({label:c.name,action:()=>selectCase(key)}));
if(research)pair().stations.filter(s=>s.station.toLowerCase().includes(text)&&s.longitude!=null).forEach(s=>options.push({label:`${s.station} · GNSS station`,action:()=>selectStation(s.station,true)}));
if(!options.length){const p=document.createElement('p');p.textContent='No matching study or station.';p.style.padding='6px';r.append(p);}options.forEach(o=>{const b=document.createElement('button');b.textContent=o.label;b.onclick=()=>{o.action();r.hidden=true;e.target.value='';};r.append(b);});});
$('#search').addEventListener('keydown',e=>{if(e.key==='Escape')$('#search-results').hidden=true;if(e.key==='Enter')$('#search-results button')?.click();if(e.key==='ArrowDown')$('#search-results button')?.focus();});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#search-results').hidden=true;});
$('#download-evidence').onclick=()=>{if(!research)return;const p=pair(),payload={project:'TerraShift',status:'UNVALIDATED_RESEARCH',science_validated:false,total_displacement_uncertainty_mm:null,study:cases[activeCase],selection,...(activeCase==='california'?{granule:p.granule,before:p.before,after:p.after,reference:p.reference,comparison_count:p.count,rmse_mm:p.rmse,stations:p.stations}:{}),sources:['https://nisar-docs.asf.alaska.edu/gunw/',research.gnss_source]};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`terrashift-${activeCase}-evidence.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function message(text){$('#map-message').textContent=text;$('#map-message').hidden=false;}
async function init(){
try{const r=await fetch('research-data.json');if(!r.ok)throw Error('Research unavailable');research=await r.json();summary();}catch(e){$('#inspector-content').innerHTML='<h2>Evidence unavailable.</h2><p class="inspector-note">The research export could not load. Refresh to try again. No substitute data is shown.</p>';$('#system-status').textContent='DATA LOAD FAILED';message('Research evidence could not load. Please refresh.');return;}
if(!maplibregl.Map){message('The map library could not load. Station evidence remains available.');$('#system-status').textContent='MAP UNAVAILABLE';return;}
try{map=new maplibregl.Map({container:'map',center:[-120.35,36.5],zoom:8.4,maxZoom:16,minZoom:2,attributionControl:true,style:{version:8,sources:{dark:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'},satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,attribution:'Imagery © Esri, Maxar, Earthstar Geographics'}},layers:[{id:'dark',type:'raster',source:'dark',paint:{'raster-saturation':-1,'raster-brightness-max':.3}},{id:'satellite',type:'raster',source:'satellite',paint:{'raster-saturation':-.78,'raster-brightness-max':.45,'raster-contrast':.1}}]}});
map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');
map.on('load',()=>{const p=pair();map.addSource('coherence',{type:'image',url:p.image,coordinates:p.coordinates});map.addLayer({id:'coherence-layer',type:'raster',source:'coherence',paint:{'raster-opacity':.75,'raster-resampling':'nearest','raster-fade-duration':0}});map.addSource('study-area',{type:'geojson',data:polygon(cases.california.bbox)});map.addLayer({id:'area-outline',type:'line',source:'study-area',paint:{'line-color':'#90dcc7','line-width':1.2,'line-dasharray':[4,4],'line-opacity':.8}});ready=true;$('#system-status').textContent='RESEARCH DATA READY';updateLayers();fit();});
map.on('mousemove',e=>$('#coordinates').textContent=`${e.lngLat.lat.toFixed(5)}° LAT   ${e.lngLat.lng.toFixed(5)}° LON`);map.on('click',e=>inspectPixel(e.lngLat.lng,e.lngLat.lat));let errors=0;map.on('error',()=>{if(++errors>=3)$('#system-status').textContent='SOME MAP RESOURCES UNAVAILABLE';});
}catch(e){message('Interactive mapping needs WebGL. Try another browser; the evidence inspector remains available.');$('#system-status').textContent='MAP UNAVAILABLE';}}
init();
